# Generated by Django 4.2.4 on 2023-10-04 19:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_catalogo', models.CharField(max_length=255)),
                ('archivo', models.FileField(upload_to='archivos_excel/')),
            ],
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=255)),
                ('nombre', models.CharField(max_length=255)),
                ('categoria', models.CharField(choices=[('ASV', 'Activo'), ('PSV', 'Pasivo'), ('PTR', 'Patrimonio'), ('ING', 'Ingresos'), ('GST', 'Gastos')], default='PSV', max_length=5)),
                ('subcategoria', models.CharField(choices=[('NNG', 'Sin SubCategoria'), ('ACTC', 'Activo Corriente'), ('ACTNC', 'Activo No Corriente'), ('PSVC', 'Pasivo Corriente'), ('PSVNC', 'Pasivo No Corriente')], default='NNG', max_length=5)),
                ('catalago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuentas', to='contabilidad.catalogo')),
            ],
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=9)),
                ('descripcion', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=250)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('tipo_transaccion', models.CharField(choices=[('CMP', 'Compra'), ('VNT', 'Venta')], default='VNT', max_length=3)),
                ('naturaleza', models.CharField(choices=[('CRD', 'Credito'), ('DBT', 'Debito')], default='CRD', max_length=3)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones', to='contabilidad.cuenta')),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Propietario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(max_length=255)),
                ('catalogo_empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='contabilidad.catalogo')),
                ('propietario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='contabilidad.propietario')),
            ],
        ),
    ]
