# Generated by Django 4.2.6 on 2023-10-12 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cuenta',
            old_name='catalago',
            new_name='catalogo',
        ),
        migrations.AlterField(
            model_name='catalogo',
            name='nombre_catalogo',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='categoria',
            field=models.CharField(choices=[('ASV', 'Activo'), ('PSV', 'Pasivo'), ('PTR', 'Patrimonio'), ('CRD', 'Cuentas de Resultados Deudoras'), ('CRA', 'Cuentas de Resultados Acreedoras')], default='PSV', max_length=5),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='subcategoria',
            field=models.CharField(choices=[('NNG', 'Sin SubCategoria'), ('ACTC', 'Activo Corriente'), ('ACTNC', 'Activo No Corriente'), ('PSVC', 'Pasivo Corriente'), ('PSVNC', 'Pasivo No Corriente'), ('CTS', 'COSTOS DE VENTA'), ('GTOP', 'Gastos Operacionales'), ('INOP', 'Ingresos Operacionales')], default='NNG', max_length=5),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='tipo_transaccion',
            field=models.CharField(choices=[('CMP', 'Compra'), ('VNT', 'Venta'), ('OPE', 'Operacional')], default='VNT', max_length=3),
        ),
    ]
