# Generated by Django 4.2.6 on 2023-10-14 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0002_rename_catalago_cuenta_catalogo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogo',
            name='nombre_catalogo',
            field=models.CharField(blank=True, default='catalogo', max_length=255),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='categoria',
            field=models.CharField(choices=[('BAG', 'Balance General'), ('ASV', 'Activo'), ('PSV', 'Pasivo'), ('PTR', 'Patrimonio'), ('ESR', 'Estado de Resultados'), ('CRD', 'Cuentas de Resultados Deudoras'), ('CRA', 'Cuentas de Resultados Acreedoras')], default='PSV', max_length=5),
        ),
    ]
