# Generated by Django 4.2.4 on 2023-10-17 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0003_alter_catalogo_nombre_catalogo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='sector',
            field=models.CharField(choices=[('MNR', 'Minería')], default='MNR', max_length=5),
        ),
    ]
