# Generated by Django 4.2.4 on 2023-10-19 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0004_empresa_sector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='subcategoria',
            field=models.CharField(choices=[('NNG', 'Sin SubCategoria'), ('ACTC', 'Activo Corriente'), ('ACTNC', 'Activo No Corriente'), ('INVT', 'Inventario'), ('PSVC', 'Pasivo Corriente'), ('PSVNC', 'Pasivo No Corriente'), ('CTS', 'COSTOS DE VENTA'), ('GTOP', 'Gastos Operacionales'), ('INOP', 'Ingresos Operacionales')], default='NNG', max_length=5),
        ),
        migrations.CreateModel(
            name='Ratio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_ratio', models.CharField(choices=[('PRBCD', 'Prueba Ácida')], default='PRBCD', max_length=5)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=9)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratios', to='contabilidad.empresa')),
            ],
        ),
    ]
