# Generated by Django 4.2.4 on 2023-10-19 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0005_alter_cuenta_subcategoria_ratio'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta',
            name='cuenta_ratio',
            field=models.CharField(choices=[('NNG', 'Ninguna'), ('ACTC', 'Activo Corriente'), ('PSVC', 'Pasivo Corriente'), ('INVT', 'Inventario')], default='NNG', max_length=5),
        ),
    ]
