# Generated by Django 4.2.6 on 2023-10-24 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0006_cuenta_cuenta_ratio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='cuenta_ratio',
            field=models.CharField(choices=[('NNG', 'Ninguna'), ('ACTC', 'Activo Corriente'), ('PSVC', 'Pasivo Corriente'), ('INVT', 'Inventario'), ('ACTV', 'Activo Totales'), ('EFCT', 'Efectivo'), ('VLRS', 'Valores a Corto Plazo'), ('CSTDV', 'Costo de ventas'), ('VNTSN', 'Ventas Netas'), ('CMPRS', 'Compras'), ('CNTAPP', 'Cuentas por pagar comerciales')], default='NNG', max_length=6),
        ),
        migrations.AlterField(
            model_name='ratio',
            name='nombre_ratio',
            field=models.CharField(choices=[('PRBCD', 'Prueba Ácida'), ('RTINV', 'Rotación de inventarios')], default='PRBCD', max_length=5),
        ),
    ]
