# Generated by Django 4.2.6 on 2023-11-02 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0007_alter_cuenta_cuenta_ratio_alter_ratio_nombre_ratio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='cuenta_ratio',
            field=models.CharField(choices=[('NNG', 'Ninguna'), ('ACTC', 'Activo Corriente'), ('PSVC', 'Pasivo Corriente'), ('INVT', 'Inventario'), ('ACTV', 'Activo Totales'), ('EFCT', 'Efectivo'), ('VLRS', 'Valores a Corto Plazo'), ('CSTDV', 'Costo de ventas'), ('VNTSN', 'Ventas Netas'), ('CMPRS', 'Compras'), ('CNTAPP', 'Cuentas por pagar comerciales'), ('CNTAPC', 'Cuentas por cobrar comerciales')], default='NNG', max_length=6),
        ),
    ]
