# Generated by Django 4.2.6 on 2023-11-02 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0008_alter_cuenta_cuenta_ratio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='sector',
            field=models.CharField(choices=[('MNR', 'Minería'), ('TRM', 'Turismo')], default='MNR', max_length=5),
        ),
    ]
