# Generated by Django 4.2.4 on 2023-11-05 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0009_alter_empresa_sector'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta',
            name='cuenta_av',
            field=models.CharField(choices=[('NNG', 'Ninguna'), ('TTACT', 'Total Activos'), ('TTPSV', 'Total Pasivos'), ('TTCPT', 'Total Capital'), ('VNTST', 'Ventas Totales')], default='NNG', max_length=6),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='subcategoria',
            field=models.CharField(choices=[('NNG', 'Sin SubCategoria'), ('ACTC', 'Activo Corriente'), ('ACTNC', 'Activo No Corriente'), ('INVT', 'Inventario'), ('PSVC', 'Pasivo Corriente'), ('PSVNC', 'Pasivo No Corriente'), ('CTS', 'COSTOS DE VENTA'), ('GTOP', 'Gastos Operacionales'), ('INOP', 'Ingresos Operacionales'), ('TTPSV', 'Total Capital'), ('UTLDD', 'Utilidad Neta')], default='NNG', max_length=5),
        ),
    ]
